#ifndef GAME_ENTITY_CHARACTERENTITY_STATES_H_INCLUDED
#define GAME_ENTITY_CHARACTERENTITY_STATES_H_INCLUDED

#include "States/Movement/Idle.h"
#include "States/Movement/Run.h"

#endif // GAME_ENTITY_CHARACTERENTITY_STATES_H_INCLUDED
